set -g mouse on

# Scroll back Size
set -g history-limit 10000

# Remap Prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
set -g pane-base-index 1

set-option -g allow-passthrough on

set -g default-terminal "xterm-256color"
#set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"

set-option -g repeat-time 0

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

#### basic settings
set-option -g status-justify "left"
#set-option utf8-default on
#set-option -g mouse-select-pane
set-window-option -g mode-keys vi
#set-window-option -g utf8 on

# look'n feel
set-option -g status-fg white
set-option -g status-bg '#131a24'
set-option -g history-limit 64096

set -sg escape-time 0

## COLOUR

# NightFox Palette
#  black   = Shade.new("#393b44", 0.15, -0.15),
#  red     = Shade.new("#c94f6d", 0.15, -0.15),
#  green   = Shade.new("#81b29a", 0.10, -0.15),
#  yellow  = Shade.new("#dbc074", 0.15, -0.15),
#  blue    = Shade.new("#719cd6", 0.15, -0.15),
#  magenta = Shade.new("#9d79d6", 0.30, -0.15),
#  cyan    = Shade.new("#63cdcf", 0.15, -0.15),
#  white   = Shade.new("#dfdfe0", 0.15, -0.15),
#  orange  = Shade.new("#f4a261", 0.15, -0.15),
#  pink    = Shade.new("#d67ad2", 0.15, -0.15),
#
#  comment = "#738091",
#
#  bg0     = "#131a24", -- Dark bg (status line and float)
#  bg1     = "#192330", -- Default bg
#  bg2     = "#212e3f", -- Lighter bg (colorcolm folds)
#  bg3     = "#29394f", -- Lighter bg (cursor line)
#  bg4     = "#39506d", -- Conceal, border fg
#
#  fg0     = "#d6d6d7", -- Lighter fg
#  fg1     = "#cdcecf", -- Default fg
#  fg2     = "#aeafb0", -- Darker fg (status line)
#  fg3     = "#71839b", -- Darker fg (line numbers, fold colums)
#
#  sel0    = "#2b3b51", -- Popup bg, visual selection bg
#  sel1    = "#3c5372", -- Popup sel bg, search bg

set -g status-interval 1
set -g status-left '#[bg=#81b29a]#[fg=#222222]#{?client_prefix,#[bg=#c94f6d],}  🚀  '
set-window-option -g window-status-style fg='#ffffff',bg='#131a24'
set-window-option -g window-status-current-style fg='#111111',bg='#719cd6'

set -g window-status-current-format "#[fg=#131a24]#[bg=#719cd6]#[fg=#111111]#[bg=#719cd6] #I #W #[fg=#719cd6]#[bg=#131a24]"
set -g window-status-format "#[fg=#ffffff]#[bg=#131a24]#I #W#[fg=#131a24] "

set -g message-style bg='#777777',fg='#ffffff'

set -g status-right '#[fg=#131a24,bg=#131a24] '
set -ga status-right '#[fg=#212e3f,bg=#131a24]#[fg=#d6d6d7,bg=#212e3f] #(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") '
set -ga status-right '#[fg=#29394f,bg=#212e3f]#[fg=#ffffff,bg=#29394f] %a %H:%M #[fg=#ffffff]%Y/%m/%d '

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"
